export const dataTableInventory = [
  {
    no: 1,
    name: 'Tanner',
    shelf: 'Linsley',
    unit: 33,
    open: 100,
    change: 50,
    balance: 9999,
    price: 1222,
    total: 1231,
  },
];

export const dataTableShelf = [
  {
    no: 1,
    name: 'Tanner',
    shelf: 'Linsley',
    unit: 33,
    quantity: 100,
    balance: 9999,
    price: 1222,
  },
  {
    no: 2,
    name: 'Tanner',
    shelf: 'Linsley',
    unit: 33,
    quantity: 100,
    balance: 9999,
    price: 1222,
  },
  {
    no: 3,
    name: 'Tanner',
    shelf: 'Linsley',
    unit: 33,
    quantity: 100,
    balance: 9999,
    price: 1222,
  },
  {
    no: 4,
    name: 'Tanner',
    shelf: 'Linsley',
    unit: 33,
    quantity: 100,
    balance: 9999,
    price: 1222,
  },
  {
    no: 5,
    name: 'Tanner',
    shelf: 'Linsley',
    unit: 33,
    quantity: 100,
    balance: 9999,
    price: 1222,
  },
  {
    no: 6,
    name: 'Tanner',
    shelf: 'Linsley',
    unit: 33,
    quantity: 100,
    balance: 9999,
    price: 1222,
  },
  {
    no: 7,
    name: 'Tanner',
    shelf: 'Linsley',
    unit: 33,
    quantity: 100,
    balance: 9999,
    price: 1222,
  },
  {
    no: 8,
    name: 'Tanner',
    shelf: 'Linsley',
    unit: 33,
    quantity: 100,
    balance: 9999,
    price: 1222,
  },
  {
    no: 9,
    name: 'Tanner',
    shelf: 'Linsley',
    unit: 33,
    quantity: 100,
    balance: 9999,
    price: 1222,
  },
  {
    no: 10,
    name: 'Tanner',
    shelf: 'Linsley',
    unit: 33,
    quantity: 100,
    balance: 9999,
    price: 1222,
  },
  {
    no: 11,
    name: 'Tanner',
    shelf: 'Linsley',
    unit: 33,
    quantity: 100,
    balance: 9999,
    price: 1222,
  },
  {
    no: 12,
    name: 'Tanner',
    shelf: 'Linsley',
    unit: 33,
    quantity: 100,
    balance: 9999,
    price: 1222,
  },
  {
    no: 13,
    name: 'Tanner',
    shelf: 'Linsley',
    unit: 33,
    quantity: 100,
    balance: 9999,
    price: 1222,
  },
];

export const columns = [
  {
    accessorKey: 'no',
    header: 'no',
    cell: (info) => <div>{info.getValue()}</div>,
  },
  {
    accessorKey: 'name',
    header: 'Name',
    cell: (info) => <div>{info.getValue()}</div>,
  },
  {
    accessorKey: 'shelf',
    header: 'Shelf',
    cell: (info) => <div>{info.getValue()}</div>,
  },
  {
    accessorKey: 'unit',
    header: 'Unit',
    cell: (info) => <div>{info.getValue()}</div>,
  },
  {
    accessorKey: 'open',
    header: 'Open',
    cell: (info) => <div>{info.getValue()}</div>,
  },
  {
    accessorKey: 'change',
    header: 'Change',
    cell: (info) => <div>{info.getValue()}</div>,
  },
  {
    accessorKey: 'balance',
    header: 'Balance',
    cell: (info) => <div>{info.getValue()}</div>,
  },
  {
    accessorKey: 'price',
    header: 'Price',
    cell: (info) => <div>{info.getValue()}</div>,
  },
  {
    accessorKey: 'total',
    header: 'Total',
    cell: (info) => <div>{info.getValue()}</div>,
  },
];
